.TH SINIT 8 sinit-VERSION
.SH NAME
sinit \- The suckless init
.SH DESCRIPTION
sinit is a simple init.  It is configured by modifying `config.h'
and recompiling the code.
.SS Init sequence
sinit will by default execute `/bin/rc.init'.  You can chain
your init scripts together at that point to allow for single-user
and multi-user mode.
.SS Signal handling
sinit will respond to the following set of signals:
.IP USR1
Default action is to initiate the shutdown sequence by
executing `/bin/rc.shutdown poweroff'.
.IP INT
Default action is to initiate the reboot sequence by
executing `/bin/rc.shutdown reboot'.
.IP CHLD
Reap children.
.SS General considerations
Running the rc.shutdown script directly is not recommended.  If any
process in your session has stale filesystem references then it is
likely your init scripts will fail to unmount the filesystem cleanly.
It is recommended to signal sinit via a wrapper script.
Similarly, sinit does not clear utmp records.  The version of getty(8)
in ubase clears the utmp entries on the specified tty before it
spawns the given program, usually login(1).
.SH SEE ALSO
killall5(8), getty(8)
